# Generated by Django 4.1.9 on 2023-05-23 05:08

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldclass",
            name="docker_path",
            field=models.FilePathField(
                max_length=500,
                path=pathlib.PureWindowsPath(
                    "C:/Users/Timmy/Desktop/yeag_ai/yeager_ai/JSONFILE"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="worldinstance",
            name="socket_path",
            field=models.FilePathField(
                max_length=500,
                path=pathlib.PureWindowsPath(
                    "C:/Users/Timmy/Desktop/yeag_ai/yeager_ai/JSONFILE"
                ),
            ),
        ),
    ]
