# Generated by Django 4.1.9 on 2023-05-27 19:55

from django.db import migrations, models
import django.utils.timezone
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_alter_worldclass_docker_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldclass',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worldclass',
            name='docker_path',
            field=models.FilePathField(max_length=500, path=pathlib.PurePosixPath('/home/wrash/Documents/Eternity/Django/YeagMain/yeag_sliper/yeager_ai/JSONFILE')),
        ),
        migrations.AlterField(
            model_name='worldinstance',
            name='socket_path',
            field=models.FilePathField(max_length=500, path=pathlib.PurePosixPath('/home/wrash/Documents/Eternity/Django/YeagMain/yeag_sliper/yeager_ai/JSONFILE')),
        ),
    ]
