# Generated by Django 4.1.9 on 2023-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_worldinstance_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldinstance',
            old_name='socket_path',
            new_name='default_preview_url',
        ),
        migrations.AddField(
            model_name='worldinstance',
            name='socket_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
