# Generated by Django 4.1.9 on 2023-06-14 06:38

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0008_alter_worldinstance_socket_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldclass",
            name="docker_path",
            field=models.FilePathField(
                max_length=500,
                path=pathlib.PureWindowsPath(
                    "C:/Users/Timmy/Desktop/Andrew/yeager_ai/JSONFILE"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="worldinstance",
            name="default_preview_file",
            field=models.FilePathField(
                max_length=500,
                path=pathlib.PureWindowsPath(
                    "C:/Users/Timmy/Desktop/Andrew/yeager_ai/JSONFILE"
                ),
            ),
        ),
    ]
