# Generated by Django 4.1.8 on 2023-05-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("amount", models.FloatField()),
                (
                    "ref_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Reference Key"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="customers email address",
                    ),
                ),
                (
                    "payment_method_types",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Payment Method"
                    ),
                ),
                (
                    "payment_intent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Payment intent"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "has_paid",
                    models.BooleanField(default=False, verbose_name="Payment Status"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
