# Generated by Django 4.1.8 on 2023-05-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agent", "0001_initial"),
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentinstance",
            name="agent_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agent.agentclass"
            ),
        ),
        migrations.AddField(
            model_name="agentinstance",
            name="world",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="world_instance_name",
                to="world.worldinstance",
            ),
        ),
        migrations.AddField(
            model_name="agentclass",
            name="memories",
            field=models.ManyToManyField(
                blank=True, related_name="agent_memory", to="world.memory"
            ),
        ),
        migrations.AddField(
            model_name="agentclass",
            name="tags",
            field=models.ManyToManyField(blank=True, to="agent.tag"),
        ),
        migrations.AddField(
            model_name="agentclass",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="world_object_tool", to="world.objectclass"
            ),
        ),
    ]
